language: scala

scala:
  - 2.11.7
  - 2.10.6

jdk:
  - oraclejdk7
  - openjdk7

addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: short-hostname

# Use new faster, container-based builds
sudo: false
